export enum GameConstants {
    Silver = "Silver",
    Quartz = "Quartz",
    Silica = "Silica",
    Gum = "Gum",
    Wax = "Wax",
    Lead = "Lead",
    ParalysisWand = "Paralysis Wand",
    DowsingRod = "Dowsing Rod",
    FocusCharm = "Focus Charm",
    SealOfBalance = "Seal of Balance",
    HermeticMirror = "Hermetic Mirror",
    VoidGate = "Void Gate",
    GoldenChassis = "Golden Chassis",
    ScryingLens = "Scrying Lens",
    CrystalBattery = "Crystal Battery",
    IcePlate = "Ice Plate",
    BraceletOfIo = "Bracelet of Io",
    ShimmeringMoonlace = "Shimmering Moonlace",
    ScaleOfTheInfinityWurm = "Scale of the Infinity Wurm",
    TheAncientRecord = "The Ancient Record",
    TheMoltenShard = "The Molten Shard",
    ActiveMonsters = "Active Monsters",
    GoodFortune = "Good Fortune",
    FleetingVisions = "Fleeting Visions",
    FoulWeather = "Foul Weather"
}
